# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8KLyre4OtzDg4lnrcnLpnKxYur8PAm1
"""

n=int(input())
sum=n*(n+1)*(2*n+1)/6
print(sum)