# -*- coding: utf-8 -*-
"""1021-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/125jY7UzlsAhmu29I-VnswFahKJ2KGNCm
"""

j=0
for n in range(1,1000):
  if n%2!=0 and n%3!=0:
    print(n,end=' ')
    j+=1
    if j%20 == 0: 
      print('\n')
