# -*- coding: utf-8 -*-
"""1021-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pLvvcMMiJ7fi1WyDrZuqRP-MqKS8FxLi
"""

n=1
while n*(n+1)*(2*n+1)/6<1000:
  n+=1
print(n)