# -*- coding: utf-8 -*-
"""1021-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3t1i_ZHD5IpnYOtb1eHfgzwFjL0BRjL
"""

m=int(input('請輸入列數(m)?'))
n=int(input('請輸入行數(n)?'))
x=input('請輸入要顯示的字元?')
for i in range(m):
        for j in range(n):
                 print(x, end = "")
        print()
