from PIL import Image
from PIL import ImageFilter

pict = Image.open('路思義.jpg')
filterPict = pict.filter(ImageFilter.BLUR)
filterPict.save('7BLUR.jpg')
filterPict = pict.filter(ImageFilter.CONTOUR)
filterPict.save('7CONTOUR.jpg')
filterPict = pict.filter(ImageFilter.DETAIL)
filterPict.save('7DETAIL.jpg')
filterPict = pict.filter(ImageFilter.EDGE_ENHANCE)
filterPict.save('7EDGE_ENHANCE.jpg')
filterPict = pict.filter(ImageFilter.EDGE_ENHANCE_MORE)
filterPict.save('7EDGE_ENHANCE_MORE.jpg')
filterPict = pict.filter(ImageFilter.EMBOSS)
filterPict.save('7EMBOSS.jpg')
filterPict = pict.filter(ImageFilter.FIND_EDGES)
filterPict.save('7FIND_EDGES.jpg')
filterPict = pict.filter(ImageFilter.SMOOTH)
filterPict.save('7SMOOTH.jpg')
filterPict = pict.filter(ImageFilter.SMOOTH_MORE)
filterPict.save('7SMOOTH_MORE.jpg')
filterPict = pict.filter(ImageFilter.SHARPEN)
filterPict.save('7SHARPEN.jpg')
